#
# the Zookeeper instance
#
# use /opt/zookeeper/bin/zkCli.sh in the image to view the contents
zookeeper:
    image: misterbisson/triton-zookeeper
    restart: always
    mem_limit: 128m
    ports:
        - 2181
        - 2888
        - 3888

#
# the Mesos master
#
master:
    image: misterbisson/triton-mesos-master
    restart: always
    mem_limit: 128m
    links:
       - zookeeper
    ports:
        - 5050
    environment:
        # see http://mesos.apache.org/documentation/latest/configuration/
        - MESOS_ZK=zk://zookeeper:2181/mesos
        - MESOS_QUORUM=1

#
# the Marathon instance
#
marathon:
    image: mesoscloud/marathon:0.10.0-ubuntu-14.04
    restart: always
    mem_limit: 128m
    links:
       - zookeeper
    ports:
        - 8080
    environment:
        # see https://mesosphere.github.io/marathon/docs/command-line-flags.html
        - MARATHON_MASTER=zk://zookeeper:2181/mesos
        - MARATHON_ZK=zk://zookeeper:2181/marathon

#
# the Mesos slave
#
slave:
    image: misterbisson/triton-mesos-slave
    restart: always
    mem_limit: 128m
    links:
       - zookeeper
    ports:
        - 5051
    environment:
        # the vars that connect this slave to the Docker API
        - TLSCA
        - TLSCERT
        - TLSKEY
        - DOCKER_HOST
        # see http://mesos.apache.org/documentation/latest/configuration/
        - MESOS_MASTER=zk://zookeeper:2181/mesos
