#
# the Zookeeper instance
#
# use /opt/zookeeper/bin/zkCli.sh in the image to view the contents
zookeeper:
    image: misterbisson/triton-zookeeper
    restart: always
    mem_limit: 128m
    ports:
        - 2181
        - 2888
        - 3888

#
# the Mesos master
#
master:
    image: misterbisson/triton-mesos-master:2015-07-06-triton
    restart: always
    mem_limit: 128m
    links:
       - zookeeper
    ports:
        - 5050
    environment:
        # see http://mesos.apache.org/documentation/latest/configuration/
        - MESOS_ZK=zk://zookeeper:2181/mesos
        - MESOS_QUORUM=1

#
# the Marathon instance
#
marathon:
    image: mesoscloud/marathon:0.10.1-ubuntu-14.04
    restart: always
    mem_limit: 128m
    links:
       - zookeeper
    ports:
        - 8080
    environment:
        # see https://mesosphere.github.io/marathon/docs/command-line-flags.html
        - MARATHON_MASTER=zk://zookeeper:2181/mesos
        - MARATHON_ZK=zk://zookeeper:2181/marathon

#
# the Mesos agent
#
agent:
    image: misterbisson/triton-mesos-agent:2015-07-06-triton-r1
    restart: always
    mem_limit: 128m
    links:
       - zookeeper
    ports:
        - 5051
    environment:
        # the vars that connect this agent to the Docker API
        - TLSCA
        - TLSCERT
        - TLSKEY
        - DOCKER_HOST
        # see http://mesos.apache.org/documentation/latest/configuration/
        - MESOS_MASTER=zk://zookeeper:2181/mesos

#
# Using a single Consul host is _highly_ discouraged, but yolo
#
consul:
    image: progrium/consul:latest
    command: -server -bootstrap -ui-dir /ui
    restart: always
    mem_limit: 128m
    ports:
        - 53
        - 8300
        - 8301
        - 8302
        - 8400
        - 8500

