#!/bin/bash

# create the necessary key files based on env vars provided in the docker run command
# ...but don't do anything if the vars are not set
if [[ -n $TLSCA && -n $TLSCERT && -n $TLSKEY ]]
then
    mkdir -p ~/.sdc/docker
    echo -e "$TLSCA" > /root/.sdc/docker/ca.pem
    echo -e "$TLSCERT" > /root/.sdc/docker/cert.pem
    echo -e "$TLSKEY" > /root/.sdc/docker/key.pem
fi

echo
echo "Joyent Triton-optimized Mesos slave starting"
echo "Docker host: $DOCKER_HOST"
echo
echo "Maximum allowed resources (change via env vars):"
echo "CPUs: $MESOS_LIMIT_CPUS"
echo "Memory: $MESOS_LIMIT_MEM"
echo "Disk: $MESOS_LIMIT_DISK"
echo

# then do the things necessary to start the Mesos slave
/usr/local/sbin/mesos-slave \
    --resources="cpus:$MESOS_RESOURCES_CPUS;mem:$MESOS_RESOURCES_MEM;disk:$MESOS_RESOURCES_DISK;ports:[0-65535]" \
    --containerizers=docker \
    --docker_socket="$DOCKER_HOST"

echo
echo "The mesos-slave unexpectedly exited. This container will now exit."